### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by evemaster** [joshlang/LettuceEncryptForReal#1]
First of all, thank you @joshlang your solution is very helpful on top of LettuceEncrypt. I spent much time to understand why the certificate can't be generated, until found the LettuceEncryptForReal. It really works :D I have a certificate (pfx file) from LetsEncrypt.

But now I'm stuck with the error ERR_CONNECTION_REFUSED. I guess LettuceEncrypt should to use the certificate automatically, right? But looks like it's not. Because I can't connect to my server using https. I going through the setup guide from LettuceEncrypt. I made "Required" steps. And just added custom directory location of files from "Optional" part of tutorial at https://github.com/natemcmaster/LettuceEncrypt#usage
No errors in logs, certificate successfully created,

In the `appsettings.json`
I had added the line `"https_port": 443,` and `"AllowedHosts": "*",`
In a docker port binded 443:433

Program.cs
```
	public class Program
	{
		public static void Main(string[] args)
		{
			CreateHostBuilder(args).Build().Run();
		}

		public static IHostBuilder CreateHostBuilder(string[] args) =>
			Host.CreateDefaultBuilder(args)
				.ConfigureWebHostDefaults(webBuilder =>
				{
					webBuilder.UseStartup<Startup>();
					webBuilder.UseKestrel();
				});
	}
```

Startup.cs
```
        public class Startup
	{
		public Startup(IConfiguration configuration)
		{
			Configuration = configuration;
		}

		public IConfiguration Configuration { get; }

		// This method gets called by the runtime. Use this method to add services to the container.
		public void ConfigureServices(IServiceCollection services)
		{
			services
				.AddLettuceEncrypt()
				.PersistDataToDirectory(new DirectoryInfo(Configuration["CertificatesDirectory"]), null);
			services.AddControllersWithViews();
		}

		// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
		public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
		{
			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
			}
			else
			{
				app.UseExceptionHandler("/Home/Error");
				// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
				app.UseHsts();
			}
			app.UseHttpsRedirection();
			app.UseStaticFiles();

			app.UseRouting();

			app.UseAuthorization();

			app.UseEndpoints(endpoints =>
			{
				endpoints.MapControllerRoute(
					name: "default",
					pattern: "{controller=Home}/{action=Index}/{id?}");
			});
		}
	}
```

Please help me to understand, what is the problem here?

**Comment by evemaster** [comment]
I found the problem. I didn't add listening on the port 443 in the Kestrel.
That's it

```
webBuilder.UseKestrel(options =>
{
	var appServices = options.ApplicationServices;
	options.Listen(IPAddress.Any, 443,
		listenOptions => listenOptions.UseHttps(connectionOptions =>
		{
			connectionOptions.UseLettuceEncrypt(appServices);
		}));
});
```

**Comment by joshlangs** [comment]
Hey!  Glad you're finding it useful.  

And glad you've solved your problem already.  I think by convention, you might just leave `.AddLettuceEncrypt()` in your `public void ConfigureServices(...)` and your leave your web builder looking something like

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
            webBuilder.UseUrls("https://+:443;http://+:80");         <--- Or let it come from environment variables
        });
```

But if it's already working for ya, no need to change it of course!
